[package]
name = "miden-multisig-app"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
miden-multisig-api = { workspace = true }
miden-multisig-store = {workspace= true}
tokio = { workspace = true, features = ["full"] }
