[package]
name = "miden-multisig-store"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
miden-client = { workspace = true, features = [ "tonic", "sqlite"] }
diesel = { version = "2", features = ["chrono"] }
diesel-async = { version = "0.5", features = ["deadpool", "postgres"] }
openssl-sys = { version = "0.9", optional = true }
pq-sys = { version = "0.7", optional = true }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
uuid = { version = "1.0", features = ["v4", "serde"] }

[dev-dependencies]
tempfile = "3.8"
tokio-test = "0.4"


